STACK_ENV ?= dev
STACK_SCRIPT := ops/scripts/stack.sh
REPO_SCRIPT := ops/scripts/repo/create.sh
TEST_SCRIPT := ops/scripts/test.sh
TEST_ARGS ?=

.PHONY: stack/%
stack/%:
	@STACK_ENV="$(STACK_ENV)" sh $(STACK_SCRIPT) "$*"

.PHONY: repo/create
repo/create:
	@OWNER="$(OWNER)" NAME="$(NAME)" DESCRIPTION="$(DESCRIPTION)" LICENSE="$(LICENSE)" PRIVATE="$(PRIVATE)" PUBLIC="$(PUBLIC)" REPO_PROVIDER="$(REPO_PROVIDER)" REPO_HOST="$(REPO_HOST)" REPO_WEB_BASE_URL="$(REPO_WEB_BASE_URL)" REPO_API_BASE_URL="$(REPO_API_BASE_URL)" REPO_GIT_REMOTE_URL="$(REPO_GIT_REMOTE_URL)" REPO_OWNER="$(REPO_OWNER)" REPO_NAME="$(REPO_NAME)" REPO_DESCRIPTION="$(REPO_DESCRIPTION)" REPO_LICENSE="$(REPO_LICENSE)" REPO_PRIVATE="$(REPO_PRIVATE)" REPO_PUBLIC="$(REPO_PUBLIC)" sh $(REPO_SCRIPT)

.PHONY: test/%
test/%:
	@TEST_ENV="$(TEST_ENV)" TEST_ARGS="$(TEST_ARGS)" sh $(TEST_SCRIPT) "$*"
